config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root :to => "campaigns#index", :as => "authenticated_root"
  end

  root 'landing#index'

  resources :locations

  resources :npcs

  
  resources :maps

  resources :campaigns

  resources :characters

  devise_for :users

  get 'tools/' => "application#tools"

  get 'campaign/1' => "application#testmap"

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :characters
  has_many :users, through: :characters
  has_many :maps
  has_many :npcs
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :campaign
  belongs_to :user
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :map
	has_many :sublocations, class_name: "Location", foreign_key: "superlocation_id"
	belongs_to :superlocation, class_name: "Location"
end

app/models/map.rb
class Map < ActiveRecord::Base
	belongs_to :campaign
	has_attached_file :image
end

app/models/npc.rb
class Npc < ActiveRecord::Base
	belongs_to :campaign
	belongs_to :map
	belongs_to :location
	has_attached_file :character_sheet
	has_attached_file :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :characters
  has_many :users, through: :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  # protect_from_forgery with: :exception
  # before_filter :authenticate_user! # This is kind of overkill, but oh well. :/

  def index
  end

  def tools
    render layout: 'tools'
  end

  def testmap
    render layout: 'testmap'
  end
  
  def after_sign_in_path_for(resource)
    '/campaigns'
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @campaigns = Campaign.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @campaigns }
      format.json { render :json => @campaigns }
    end
  end

  def show
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @campaign }
      format.json { render :json => @campaign }
    end
  end

  def new
    @campaign = Campaign.new
    respond_with(@campaign)
  end

  def edit
  end

  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.save
    respond_with(@campaign)
  end

  def update
    @campaign.update(campaign_params)
    respond_with(@campaign)
  end

  def destroy
    @campaign.destroy
    respond_with(@campaign)
  end

  private
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    def campaign_params
      params.require(:campaign).permit(:name, :notes)
    end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @characters = Character.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @characters }
      format.json { render :json => @characters }
    end
  end

  def show
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @character }
      format.json { render :json => @character }
    end
  end

  def new
    @character = Character.new
    respond_with(@character)
  end

  def edit
  end

  def create
    @character = Character.new(character_params)
    @character.save
    respond_with(@character)
  end

  def update
    @character.update(character_params)
    respond_with(@character)
  end

  def destroy
    @character.destroy
    respond_with(@character)
  end

  private
    def set_character
      @character = Character.find(params[:id])
    end

    def character_params
      params.require(:character).permit(:user_id, :campaign_id, :role, :name, :notes)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
  end
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @locations = Location.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @locations }
      format.json { render :json => @locations }
    end
  end

  def show
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @location }
      format.json { render :json => @location }
    end
  end

  def new
    @location = Location.new
    respond_with(@location)
  end

  def edit
  end

  def create
    @location = Location.new(location_params)
    @location.save
    respond_with(@location)
  end

  def update
    @location.update(location_params)
    respond_with(@location)
  end

  def destroy
    @location.destroy
    respond_with(@location)
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:map_id, :superlocation_id, :x_coordinate, :y_coordinate, :name, :type, :notes, :image)
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @maps = Map.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @maps }
      format.json { render :json => @maps }
    end
  end

  def show
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @map }
      format.json { render :json => @map }
    end
  end

  def new
    @map = Map.new
    respond_with(@map)
  end

  def edit
  end

  def create
    @map = Map.new(map_params)
    @map.save
    respond_with(@map)
  end

  def update
    @map.update(map_params)
    respond_with(@map)
  end

  def destroy
    @map.destroy
    respond_with(@map)
  end

  private
    def set_map
      @map = Map.find(params[:id])
    end

    def map_params
      params.require(:map).permit(:campaign_id, :notes)
    end
end

app/controllers/np_cs_controller.rb
class NpCsController < ApplicationController
  before_action :set_npc, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @npcs = Npc.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @npcs }
      format.json { render :json => @npcs }
    end
  end

  def show
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @npc }
      format.json { render :json => @npc }
    end
  end

  def new
    @npc = Npc.new
    respond_with(@npc)
  end

  def edit
  end

  def create
    @npc = Npc.new(npc_params)
    @npc.save
    respond_with(@npc)
  end

  def update
    @npc.update(npc_params)
    respond_with(@npc)
  end

  def destroy
    @npc.destroy
    respond_with(@npc)
  end

  private
    def set_npc
      @npc = Npc.find(params[:id])
    end

    def npc_params
      params.require(:npc).permit(:map_id, :location_id, :name, :notes, :character_sheet, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/np_cs_helper.rb
module NpCsHelper
end

app/views/application/testmap.html.erb
<button id="city">+ city</button>

	<div id="map">
	<div id="content">
		<%= image_tag "gnomon.jpg" %>
		<h1 class="edit_title">world map</h1><a type="button" class="close ">x</a> <br>
		<p class="edit_area"></p>
		<br>
		
	</div>
		<div id='wrap'><%= image_tag "map.jpg" %></img></div>

	</div>

app/views/application/tools.html.erb
<div style="display:none">
&nbsp;
</div>

app/views/campaigns/_form.html.erb
<%= form_for(@campaign) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ymir", root_path, :class => "navbar-brand" %>
    </div>  
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Campaigns</a></li>
        <li><a href="#">Tools</a></li>
        </li>
      </ul>
      <div class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <%= button_to "Sign Out", destroy_user_session_path, :class => "btn sign-in-up btn-primary", :method => :delete  %>
        </div>
      </form>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

<br><br>

<div class="container">
  <div class="row">

<br>
<h1>Editing Campaign</h1>


<%= render 'form' %>

<a href="/campaign/1">Show</a> |
<%= link_to 'Back', campaigns_path %>

</div>
</div>

app/views/campaigns/index.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ymir", root_path, :class => "navbar-brand" %>
    </div>  
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Campaigns</a></li>
        <li><a href="#">Tools</a></li>
        </li>
      </ul>
      <div class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <%= button_to "Sign Out", destroy_user_session_path, :class => "btn sign-in-up btn-primary", :method => :delete  %>
        </div>
      </form>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

<br><br>

<div class="container">
  <div class="row"> <br>
    <h1>Campaigns</h1>
    <div style="float:right; position:relative; top:-3rem;"><%= button_to '+ New Campaign', new_campaign_path, :class => "btn sign-in-up-form btn-primary", :method => :get %></div>
  </div>
  <div class="row">
    <% @campaigns.each do |campaign| %>
      <div class="col-md-4" style="background:#005792; overflow:hidden; height: 250px; border: 1px solid black;">
      <br>

        <h2 class="text-center"><%= campaign.name %></h2>
        <div class="text-center"><%= campaign.notes.truncate(50, omission: '... (continued)') %></div>
        <br>
        <div class="text-center" style="background: #E7E7E7;
padding: 2rem;
position: relative;
top: 6.5rem;
width: 110%;
left: -2rem;">
          <a href="/campaign/1">Show</a> //
          <%= link_to 'Edit', edit_campaign_path(campaign) %> // 
          <%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <br>
  <br>
  <hr>

  <footer>
    <p>&copy; Ymir - CodeDay Portland 2014</p>
  </footer>
</div> <!-- /container -->

<!-- <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>-->

app/views/campaigns/new.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ymir", root_path, :class => "navbar-brand" %>
    </div>  
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Campaigns</a></li>
        <li><a href="#">Tools</a></li>
        </li>
      </ul>
      <div class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <%= button_to "Sign Out", destroy_user_session_path, :class => "btn sign-in-up btn-primary", :method => :delete  %>
        </div>
      </form>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

<br><br>

<div class="container">
  <div class="row">


<br>
<h1>New Campaign</h1>



<%= render 'form' %>

<%= link_to 'Back', campaigns_path %>


</div>
</div>

app/views/campaigns/show.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ymir", root_path, :class => "navbar-brand" %>
    </div>  
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Campaigns</a></li>
        <li><a href="#">Tools</a></li>
        </li>
      </ul>
      <div class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <%= button_to "Sign Out", destroy_user_session_path, :class => "btn sign-in-up btn-primary", :method => :delete  %>
        </div>
      </form>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

<br><br>
<br><br><br>


<div class="container">
  <div class="row">

<div class="col-md-12">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @campaign.name %>
	</p>

	<p>
	  <strong>Notes:</strong>
	  <%= @campaign.notes %>
	</p>

	<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
	<%= link_to 'Back', campaigns_path %>
</div>

</div>
</div>

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :campaign_id %><br>
    <%= f.number_field :campaign_id %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.number_field :role %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Characters</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Campaign</th>
      <th>Role</th>
      <th>Name</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= character.user_id %></td>
        <td><%= character.campaign_id %></td>
        <td><%= character.role %></td>
        <td><%= character.name %></td>
        <td><%= character.notes %></td>
        <td><%= link_to 'Show', character %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @character.user_id %>
</p>

<p>
  <strong>Campaign:</strong>
  <%= @character.campaign_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @character.role %>
</p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @character.notes %>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/landing/index.html.erb
<style type="text/css" media="screen">
  body{
    background: url("http://cdn.wonderfulengineering.com/wp-content/uploads/2014/06/earth-wallpapers-14.jpg");
    color: #FFF;
    text-shadow: 1px 1px 5px #000;  
    background-size: cover;
  }
</style>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ymir", root_path, :class => "navbar-brand" %>
    </div>  
    <div id="navbar" class="navbar-collapse collapse">
      <div class="navbar-form navbar-right" role="form">
        <div class="form-group">
          <%= button_to "New User", new_user_registration_path, :class => "btn sign-in-up btn-primary", :method => :get  %>
        </div>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <div class="form-group">
          <%= button_to "Sign In", new_user_session_path, :class => "btn sign-in-up btn-primary", :method => :get  %>
        </div>
      </form>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="container">
  <h1 class="text-center big-kahuna">Build your world.</h1>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 text-center">
      <p class="tall">
        <em>
          From Ymir’s flesh the earth was created<br>
          And from his blood the sea,<br>
          Mountains from bone,<br>
          Trees from hair,<br>
          And from his skull the sky.<br>

          And from his eyebrows the blithe gods made<br>
          Midgard, home of the sons of men<br>
          And from his brains<br>
          They sculpted the grim clouds.<br>
        </em>
      </p>
    </div>
  </div>
  <br>
  <hr>

  <footer>
    <p>&copy; Ymir - CodeDay Portland 2014</p>
  </footer>
</div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ymir - Build your world.</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :map_id %><br>
    <%= f.number_field :map_id %>
  </div>
  <div class="field">
    <%= f.label :superlocation_id %><br>
    <%= f.number_field :superlocation_id %>
  </div>
  <div class="field">
    <%= f.label :x_coordinate %><br>
    <%= f.number_field :x_coordinate %>
  </div>
  <div class="field">
    <%= f.label :y_coordinate %><br>
    <%= f.number_field :y_coordinate %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Map</th>
      <th>Superlocation</th>
      <th>Name</th>
      <th>Type</th>
      <th>Notes</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.map_id %></td>
        <td><%= location.superlocation_id %></td>
        <td><%= location.name %></td>
        <td><%= location.type %></td>
        <td><%= location.notes %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Map:</strong>
  <%= @location.map_id %>
</p>

<p>
  <strong>Superlocation:</strong>
  <%= @location.superlocation_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @location.type %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @location.notes %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Maps</h1>

<table>
  <thead>
    <tr>
      <th>Campaign</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.campaign_id %></td>
        <td><%= map.notes %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Campaign:</strong>
  <%= @map.campaign_id %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @map.notes %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>

app/views/np_cs/edit.html.erb
<h1>Editing Npc</h1>

<%= render 'form' %>

<%= link_to 'Show', @npc %> |
<%= link_to 'Back', npcs_path %>

app/views/np_cs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Npcs</h1>

<table>
  <thead>
    <tr>
      <th>Map</th>
      <th>Location</th>
      <th>Name</th>
      <th>Notes</th>
      <th>Character sheet</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @npcs.each do |npc| %>
      <tr>
        <td><%= npc.map_id %></td>
        <td><%= npc.location_id %></td>
        <td><%= npc.name %></td>
        <td><%= npc.notes %></td>
        <td><%= npc.character_sheet %></td>
        <td><%= npc.image %></td>
        <td><%= link_to 'Show', npc %></td>
        <td><%= link_to 'Edit', edit_npc_path(npc) %></td>
        <td><%= link_to 'Destroy', npc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Npc', new_npc_path %>

app/views/np_cs/new.html.erb
<h1>New Npc</h1>

<%= render 'form' %>

<%= link_to 'Back', npcs_path %>

app/views/np_cs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Map:</strong>
  <%= @npc.map_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @npc.location_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @npc.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @npc.notes %>
</p>

<p>
  <strong>Character sheet:</strong>
  <%= @npc.character_sheet %>
</p>

<p>
  <strong>Image:</strong>
  <%= @npc.image %>
</p>

<%= link_to 'Edit', edit_npc_path(@npc) %> |
<%= link_to 'Back', npcs_path %>